version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: "Build"
          command: go build -v ./...

  test:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: Install Task
          command: |
            sudo apt-get update && sudo apt-get install -y task
      - run:
          name: Run Tests
          command: task test

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build