version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.24
    steps:
      - checkout
      - run:
          name: "Build"
          command: go build -v ./...
      - run:
          name: "Run Tests"
          command: |
            go install github.com/go-task/task/v3/cmd/task@latest
            task test

workflows:
  build-and-test:
    jobs:
      - build