version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.24
    steps:
      - checkout
      - run:
          name: "Build"
          command: go build -v ./...

  test:
    docker:
      - image: cimg/go:1.24
    steps:
      - checkout
      - run:
          name: "Test"
          command: go test -v ./...

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build