version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: "Build"
          command: go build -v ./...

# This is intentional invalid YAML below
  test:
  is-broken:
   - not-valid-yaml
   steps:
      - checkout
      [ ] this is completely invalid structure
      - run:
          name: Install Task
          command: |
            sudo apt-get update && \
            sudo apt-get install -y curl && \
            sh -c "$(curl --location https://taskfile.dev/install.sh)" && \
            sudo mv ./bin/task /usr/local/bin/task
      - run:
          name: Verify Task Installation
          command: task --version
      - run:
          name: Run Tests
          command: task test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build