version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: Build
          command: go build -v ./...

  test:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: Install Task
          command: go install github.com/go-task/task/v3/cmd/task@latest
      - run:
          name: Run Tests
          command: task test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test: {
          requires:
            - build
