version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.24
    steps:
      - checkout
      - run:
          name: "Build"
          command: go build -v ./...

  test:
    docker:
      - image: cimg/go:1.24
    steps:
      - checkout
      - run:
          name: Install Task
          command: go install github.com/go-task/task/v3/cmd/task@latest
      - run:
          name: Run Tests
          command: task test

  wait-30-seconds:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Wait 10 seconds"
          command: |
            echo "Starting 10 second wait..."
            sleep 10
            echo "Wait complete - returning success!"
            exit 1

  post-approval-job:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Job after approval"
          command: |
            echo "This job runs after manual approval"
            echo "Success!"

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - wait-30-seconds  # This runs in parallel with other jobs
      - approve-me:
          type: approval
          requires:
            - build
      - post-approval-job:
          requires:
            - approve-me