version: 2.1
jobs:
  hello_world_5:
    docker:
      - image: python:3.8-slim
    steps:
      - run:
          name: Sleep 3 seconds and Print Hello Again
          command: |
            sleep 3
            echo "Hello, Again!"
      - run:
          name: Sleep 3 seconds and Print Hello Once More
          command: |
            sleep 3
            echo "Hello, Once More!"
workflows:
  version: 2
  new_workflow:
    jobs:
      - hello_world_5
