version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: Build
          command: go build -v ./...

  test:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: Install Task
          command: |
            sudo sh -c "$(curl --location https://taskfile.dev/install.sh) -- -d"
      - run:
          name: Run Tests
          command: /usr/local/bin/task test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build